/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// NFInstancesStoreApiService is a service that implents the logic for the NFInstancesStoreApiServicer
// This service should implement the business logic for every endpoint for the NFInstancesStoreApi API. 
// Include any external packages or services that will be required by this service.
type NFInstancesStoreApiService struct {
}

// NewNFInstancesStoreApiService creates a default api service
func NewNFInstancesStoreApiService() NFInstancesStoreApiServicer {
	return &NFInstancesStoreApiService{}
}

// GetNFInstances - Retrieves a collection of NF Instances
func (s *NFInstancesStoreApiService) GetNFInstances(nfType NfType, limit int32) (interface{}, error) {
	// TODO - update GetNFInstances with the required logic for this service method.
	// Add api_nf_instances_store_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetNFInstances' not implemented")
}

// OptionsNFInstances - Discover communication options supported by NRF for NF Instances
func (s *NFInstancesStoreApiService) OptionsNFInstances() (interface{}, error) {
	// TODO - update OptionsNFInstances with the required logic for this service method.
	// Add api_nf_instances_store_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'OptionsNFInstances' not implemented")
}
