/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// SubscriptionIDDocumentApiService is a service that implents the logic for the SubscriptionIDDocumentApiServicer
// This service should implement the business logic for every endpoint for the SubscriptionIDDocumentApi API. 
// Include any external packages or services that will be required by this service.
type SubscriptionIDDocumentApiService struct {
}

// NewSubscriptionIDDocumentApiService creates a default api service
func NewSubscriptionIDDocumentApiService() SubscriptionIDDocumentApiServicer {
	return &SubscriptionIDDocumentApiService{}
}

// RemoveSubscription - Deletes a subscription
func (s *SubscriptionIDDocumentApiService) RemoveSubscription(subscriptionID string) (interface{}, error) {
	// TODO - update RemoveSubscription with the required logic for this service method.
	// Add api_subscription_id_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'RemoveSubscription' not implemented")
}

// UpdateSubscription - Updates a subscription
func (s *SubscriptionIDDocumentApiService) UpdateSubscription(subscriptionID string, patchItem []PatchItem) (interface{}, error) {
	// TODO - update UpdateSubscription with the required logic for this service method.
	// Add api_subscription_id_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'UpdateSubscription' not implemented")
}
