/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A SubscriptionsCollectionApiController binds http requests to an api service and writes the service results to the http response
type SubscriptionsCollectionApiController struct {
	service SubscriptionsCollectionApiServicer
}

// NewSubscriptionsCollectionApiController creates a default api controller
func NewSubscriptionsCollectionApiController(s SubscriptionsCollectionApiServicer) Router {
	return &SubscriptionsCollectionApiController{ service: s }
}

// Routes returns all of the api route for the SubscriptionsCollectionApiController
func (c *SubscriptionsCollectionApiController) Routes() Routes {
	return Routes{ 
		{
			"CreateSubscription",
			strings.ToUpper("Post"),
			"/nnrf-nfm/v1/subscriptions",
			c.CreateSubscription,
		},
	}
}

// CreateSubscription - Create a new subscription
func (c *SubscriptionsCollectionApiController) CreateSubscription(w http.ResponseWriter, r *http.Request) { 
	subscriptionData := &SubscriptionData{}
	if err := json.NewDecoder(r.Body).Decode(&subscriptionData); err != nil {
		w.WriteHeader(500)
		return
	}
	
	result, err := c.service.CreateSubscription(*subscriptionData)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}
