/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// SubscriptionsCollectionApiService is a service that implents the logic for the SubscriptionsCollectionApiServicer
// This service should implement the business logic for every endpoint for the SubscriptionsCollectionApi API. 
// Include any external packages or services that will be required by this service.
type SubscriptionsCollectionApiService struct {
}

// NewSubscriptionsCollectionApiService creates a default api service
func NewSubscriptionsCollectionApiService() SubscriptionsCollectionApiServicer {
	return &SubscriptionsCollectionApiService{}
}

// CreateSubscription - Create a new subscription
func (s *SubscriptionsCollectionApiService) CreateSubscription(subscriptionData SubscriptionData) (interface{}, error) {
	// TODO - update CreateSubscription with the required logic for this service method.
	// Add api_subscriptions_collection_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'CreateSubscription' not implemented")
}
