/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DefaultNotificationSubscription struct {

	NotificationType NotificationType `json:"notificationType"`

	CallbackUri string `json:"callbackUri"`

	N1MessageClass N1MessageClass `json:"n1MessageClass,omitempty"`

	N2InformationClass N2InformationClass `json:"n2InformationClass,omitempty"`
}
