/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type SubscriptionData struct {

	NfStatusNotificationUri string `json:"nfStatusNotificationUri"`

	SubscrCond OneOfNfInstanceIdCondNfTypeCondServiceNameCondAmfCondGuamiListCondNetworkSliceCondNfGroupCond `json:"subscrCond,omitempty"`

	SubscriptionId string `json:"subscriptionId"`

	ValidityTime time.Time `json:"validityTime,omitempty"`

	ReqNotifEvents []NotificationEventType `json:"reqNotifEvents,omitempty"`

	PlmnId PlmnId `json:"plmnId,omitempty"`

	NotifCondition NotifCondition `json:"notifCondition,omitempty"`

	ReqNfType NfType `json:"reqNfType,omitempty"`

	ReqNfFqdn string `json:"reqNfFqdn,omitempty"`

	ReqSnssais []Snssai `json:"reqSnssais,omitempty"`
}
