/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Ipv6PrefixRange struct {

	Start Ipv6Prefix `json:"start,omitempty"`

	End Ipv6Prefix `json:"end,omitempty"`
}
