/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type NfProfile struct {

	NfInstanceId string `json:"nfInstanceId"`

	NfType NfType `json:"nfType"`

	NfStatus NfStatus `json:"nfStatus"`

	HeartBeatTimer int32 `json:"heartBeatTimer,omitempty"`

	PlmnList []PlmnId `json:"plmnList,omitempty"`

	SNssais []Snssai `json:"sNssais,omitempty"`

	PerPlmnSnssaiList []PlmnSnssai `json:"perPlmnSnssaiList,omitempty"`

	NsiList []string `json:"nsiList,omitempty"`

	Fqdn string `json:"fqdn,omitempty"`

	InterPlmnFqdn string `json:"interPlmnFqdn,omitempty"`

	Ipv4Addresses []string `json:"ipv4Addresses,omitempty"`

	Ipv6Addresses []Ipv6Addr `json:"ipv6Addresses,omitempty"`

	AllowedPlmns []PlmnId `json:"allowedPlmns,omitempty"`

	AllowedNfTypes []NfType `json:"allowedNfTypes,omitempty"`

	AllowedNfDomains []string `json:"allowedNfDomains,omitempty"`

	AllowedNssais []Snssai `json:"allowedNssais,omitempty"`

	Priority int32 `json:"priority,omitempty"`

	Capacity int32 `json:"capacity,omitempty"`

	Load int32 `json:"load,omitempty"`

	Locality string `json:"locality,omitempty"`

	UdrInfo UdrInfo `json:"udrInfo,omitempty"`

	UdmInfo UdmInfo `json:"udmInfo,omitempty"`

	AusfInfo AusfInfo `json:"ausfInfo,omitempty"`

	AmfInfo AmfInfo `json:"amfInfo,omitempty"`

	SmfInfo SmfInfo `json:"smfInfo,omitempty"`

	UpfInfo UpfInfo `json:"upfInfo,omitempty"`

	PcfInfo PcfInfo `json:"pcfInfo,omitempty"`

	BsfInfo BsfInfo `json:"bsfInfo,omitempty"`

	ChfInfo ChfInfo `json:"chfInfo,omitempty"`

	NrfInfo NrfInfo `json:"nrfInfo,omitempty"`

	CustomInfo map[string]interface{} `json:"customInfo,omitempty"`

	RecoveryTime time.Time `json:"recoveryTime,omitempty"`

	NfServicePersistence bool `json:"nfServicePersistence,omitempty"`

	NfServices []NfService `json:"nfServices,omitempty"`

	NfProfileChangesSupportInd bool `json:"nfProfileChangesSupportInd,omitempty"`

	NfProfileChangesInd bool `json:"nfProfileChangesInd,omitempty"`

	DefaultNotificationSubscriptions []DefaultNotificationSubscription `json:"defaultNotificationSubscriptions,omitempty"`
}
