/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ChangeItem struct {

	Op ChangeType `json:"op"`

	Path string `json:"path"`

	From string `json:"from,omitempty"`

	OrigValue interface{} `json:"origValue,omitempty"`

	NewValue interface{} `json:"newValue,omitempty"`
}
