/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NrfInfo struct {

	ServedUdrInfo map[string]UdrInfo `json:"servedUdrInfo,omitempty"`

	ServedUdmInfo map[string]UdmInfo `json:"servedUdmInfo,omitempty"`

	ServedAusfInfo map[string]AusfInfo `json:"servedAusfInfo,omitempty"`

	ServedAmfInfo map[string]AmfInfo `json:"servedAmfInfo,omitempty"`

	ServedSmfInfo map[string]SmfInfo `json:"servedSmfInfo,omitempty"`

	ServedUpfInfo map[string]UpfInfo `json:"servedUpfInfo,omitempty"`

	ServedPcfInfo map[string]PcfInfo `json:"servedPcfInfo,omitempty"`

	ServedBsfInfo map[string]BsfInfo `json:"servedBsfInfo,omitempty"`

	ServedChfInfo map[string]ChfInfo `json:"servedChfInfo,omitempty"`
}
